defaultClanColor: "&5"
defaultNameColor: "&f"
colorCodes:
    - "&0"
    - "&1"
    - "&2"
    - "&3"
    - "&4"
    - "&5"
    - "&6"
    - "&7"
    - "&8"
    - "&9"
    - "&a"
    - "&b"
    - "&c"
    - "&d"
    - "&e"
    - "&f"
    - "&l"
    - "&o"
    - "&r"