# Konfiguration im YAML-Format
defaultGroupChatColor: '&5'
defaultUserChatColor: '&f'
defaultGroup: '0000-0000-0000'
chatFormat: '&7&l˅&r %c%%cc%%groupName% &7*%pc% %1$s &7&l˅&r \n&7%2$s'
colorCodes:
  - '&0'
  - '&1'
  - '&2'
  - '&3'
  - '&4'
  - '&5'
  - '&6'
  - '&7'
  - '&8'
  - '&9'
  - '&a'
  - '&b'
  - '&c'
  - '&d'
  - '&e'
  - '&f'
  - '&o'
  - '&l'
forbiddenColors:
  - '&k'
  - '&m'
  - '&n'
  - '&r'
forbiddenGroupNames:
  - 'Spieler'
  - 'Admin'
  - 'Owner'
  - 'Inhaber'
  - 'Moderator'
  - 'Administrator'
  - 'Support'
  - 'Supporter'
  - 'Hurensohn'
  - 'Huso'
  - 'Spasti'
  - 'Arschloch'